#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Acme\StandaloneBundle\App\AppKernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

set_time_limit(0);

require_once __DIR__ . '/../vendor/autoload.php';

$input = new ArgvInput();
$env = $input->getParameterOption(['--env', '-e'], getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && $env !== 'prod';

if ($debug) {
     Debug::enable();

     function sd(...$vars)
     {
         s(...$vars);
         exit;
     }
     \Kint::$aliases[] = 'sd';
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
