<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxm5j1h\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxm5j1h/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGxm5j1h.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGxm5j1h\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGxm5j1h\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gxm5j1h',
    'container.build_id' => '26cff157',
    'container.build_time' => 1536670617,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxm5j1h');
